-- ============================================================
-- VibeDonuts — Tabel `products`
-- Sumber: PRD Bagian 5 (Skema Data) + Bagian 4 (Logika Bisnis)
-- Target: Supabase (PostgreSQL) — jalankan di SQL Editor.
--
-- Catatan penamaan: nama kolom MENGIKUTI PRD apa adanya (nama, harga,
-- stok, url_foto, dst.) supaya service layer frontend (src/services/)
-- bisa dipasangkan tanpa rename.
-- Padanan istilah: nama=name · harga=price · deskripsi=description ·
-- url_foto=image_url · stok=stock · aktif=is_active ·
-- dibuat_pada/diubah_pada=created_at/updated_at
-- ============================================================

create table if not exists public.products (
  id          bigint      generated by default as identity primary key,
  category_id bigint,                                                    -- FK ke categories (blok di bawah)
  nama        text        not null check (char_length(btrim(nama)) between 3 and 100),
  slug        text        not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),  -- ramah URL, contoh: donat-tiramisu
  deskripsi   text        not null default '',
  harga       integer     not null check (harga >= 0),                   -- rupiah bulat (PRD 4.2)
  stok        integer     not null default 0 check (stok >= 0),          -- PRD 4.1: stok tidak boleh minus
  url_foto    text        not null default '',                           -- path/URL foto (upload maks 2 MB, PRD 4.4)
  aktif       boolean     not null default true,                         -- false = disembunyikan dari katalog (A-3)
  dibuat_pada timestamptz not null default now(),
  diubah_pada timestamptz not null default now()
);

-- Indeks untuk kueri katalog (P-2/P-3: filter kategori, urut terbaru, produk tampil)
create index if not exists products_category_idx on public.products (category_id);
create index if not exists products_katalog_idx  on public.products (aktif, dibuat_pada desc);

-- ============================================================
-- `diubah_pada` terisi otomatis setiap kali baris di-update
-- ============================================================
create or replace function public.vd_set_diubah_pada()
returns trigger
language plpgsql
as $$
begin
  new.diubah_pada := now();
  return new;
end;
$$;

drop trigger if exists trg_products_diubah_pada on public.products;
create trigger trg_products_diubah_pada
  before update on public.products
  for each row execute function public.vd_set_diubah_pada();

-- ============================================================
-- Relasi ke `categories` (PRD: satu kategori punya banyak produk).
-- Jalankan blok ini SETELAH tabel `categories` dibuat:
-- ============================================================
-- alter table public.products
--   add constraint products_category_id_fkey
--   foreign key (category_id) references public.categories (id)
--   on delete set null;

-- ============================================================
-- RLS Supabase — aktifkan saat frontend mulai terhubung.
-- Baca produk terbuka untuk umum (katalog P-2); policy tulis untuk
-- admin menyusul, menyesuaikan mekanisme login admin yang dipakai.
-- ============================================================
-- alter table public.products enable row level security;
-- create policy "publik bisa melihat produk"
--   on public.products for select
--   using (true);

-- ============================================================
-- (Opsional) Data awal 3 donat sesuai MVP — cocok dengan seed frontend.
-- ============================================================
-- insert into public.products (id, nama, slug, harga, stok, url_foto, aktif) values
--   (1, 'Donat Tiramisu', 'donat-tiramisu', 18000, 24,
--    'https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?auto=format&fit=crop&w=900&q=80', true),
--   (2, 'Donat Cokelat Klasik', 'donat-cokelat-klasik', 12000, 4,
--    'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80', true),
--   (3, 'Donat Strawberry Sprinkle', 'donat-strawberry-sprinkle', 15000, 0,
--    'https://images.unsplash.com/photo-1626094309830-abbb0c99da4a?auto=format&fit=crop&w=900&q=80', true)
-- on conflict (id) do nothing;
--
-- Sinkronkan sequence setelah insert dengan id eksplisit:
-- select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));
