-- ============================================================
-- VibeDonuts — Tabel pesanan, rincian, riwayat stok & pengaturan toko
-- Sumber : PRD Bagian 5 (Skema Data) + 4.1/4.2/4.3/4.4 (Logika Bisnis)
-- Target : Supabase (PostgreSQL) — jalankan SEKALI di SQL Editor,
--          SETELAH 01_products.sql dan 02_products_policies.sql.
--
-- Isi: orders, order_items, stock_logs, settings, trigger penjaga status,
--      dan 2 fungsi (RPC) atomik: vd_create_order & vd_cancel_order.
-- ============================================================

-- ---------- Tabel `orders` (PRD Bagian 5) ----------
create table if not exists public.orders (
  id                 bigint      generated by default as identity primary key,
  kode_pesanan       text        unique,                    -- VD-YYMM-id, diisi fungsi vd_create_order
  nama_pelanggan     text        not null check (char_length(btrim(nama_pelanggan)) between 3 and 100),
  no_hp              text        not null check (no_hp ~ '^[0-9]{10,15}$'),          -- PRD 4.4: minimal 10 angka
  alamat             text        not null check (char_length(btrim(alamat)) >= 10),
  catatan            text        not null default '',
  total_barang       integer     not null default 0 check (total_barang >= 0),
  ongkos_kirim       integer     not null default 0 check (ongkos_kirim >= 0),
  total_bayar        integer     not null default 0 check (total_bayar >= 0),
  status             text        not null default 'Menunggu Pembayaran'
                                 check (status in ('Menunggu Pembayaran','Menunggu Verifikasi',
                                                   'Diproses','Dikirim','Selesai','Dibatalkan')),
  url_bukti_transfer text,
  dibuat_pada        timestamptz not null default now(),
  diubah_pada        timestamptz not null default now()
);

create index if not exists orders_dibuat_idx on public.orders (dibuat_pada desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_no_hp_idx  on public.orders (no_hp);

-- ---------- Tabel `order_items` (harga & nama DIKUNCI, PRD 4.2) ----------
create table if not exists public.order_items (
  id           bigint  generated by default as identity primary key,
  order_id     bigint  not null references public.orders (id) on delete cascade,
  product_id   bigint  references public.products (id) on delete set null, -- nota tetap benar walau produk dihapus (PRD 5)
  nama_produk  text    not null,
  harga_satuan integer not null check (harga_satuan >= 0),
  jumlah       integer not null check (jumlah >= 1),
  subtotal     integer not null check (subtotal >= 0)
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- ---------- Tabel `stock_logs` (riwayat stok, PRD A-4) ----------
create table if not exists public.stock_logs (
  id           bigint      generated by default as identity primary key,
  product_id   bigint      references public.products (id) on delete cascade,
  perubahan    integer     not null,
  stok_sebelum integer     not null check (stok_sebelum >= 0),
  stok_sesudah integer     not null check (stok_sesudah >= 0),
  alasan       text        not null default '',
  user_id      bigint,
  dibuat_pada  timestamptz not null default now()
);

create index if not exists stock_logs_product_idx on public.stock_logs (product_id, dibuat_pada desc);

-- ---------- Tabel `settings` (PRD A-7) ----------
create table if not exists public.settings (
  kunci text primary key,
  nilai text not null default ''
);

insert into public.settings (kunci, nilai) values
  ('ongkos_kirim', '10000'),
  ('nomor_rekening', '1234567890'),
  ('nama_bank', 'BCA'),
  ('atas_nama', 'Rina VibeDonuts'),
  ('whatsapp_toko', '6281234567890')
on conflict (kunci) do nothing;

-- ============================================================
-- Trigger: `diubah_pada` otomatis (fungsi dipakai ulang dari 01_products.sql)
-- ============================================================
drop trigger if exists trg_orders_diubah_pada on public.orders;
create trigger trg_orders_diubah_pada
  before update on public.orders
  for each row execute function public.vd_set_diubah_pada();

-- ============================================================
-- Trigger penjaga alur status (PRD 4.3):
-- hanya boleh maju SATU langkah; "Selesai"/"Dibatalkan" terkunci;
-- "Dibatalkan" boleh dari tahap mana pun sebelum Selesai.
-- ============================================================
create or replace function public.vd_guard_order_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_flow     text[] := array['Menunggu Pembayaran','Menunggu Verifikasi','Diproses','Dikirim','Selesai'];
  v_old_step integer;
  v_new_step integer;
begin
  if new.status is distinct from old.status then
    if old.status in ('Selesai', 'Dibatalkan') then
      raise exception 'Pesanan berstatus "%" tidak bisa diubah lagi.', old.status;
    end if;

    if new.status <> 'Dibatalkan' then
      v_old_step := array_position(v_flow, old.status);
      v_new_step := array_position(v_flow, new.status);
      if v_new_step is null or v_old_step is null or v_new_step <> v_old_step + 1 then
        raise exception 'Status hanya boleh maju satu langkah, tidak boleh mundur atau melompat.';
      end if;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_orders_guard_status on public.orders;
create trigger trg_orders_guard_status
  before update on public.orders
  for each row execute function public.vd_guard_order_status();

-- ============================================================
-- Helper: satu pesanan + rinciannya dalam bentuk JSON
-- (bentuk kolom = persis skema PRD Bagian 5 agar cocok dengan frontend)
-- ============================================================
create or replace function public.vd_order_jsonb(p_order_id bigint)
returns jsonb
language sql
security definer
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id',                 o.id,
    'kode_pesanan',       o.kode_pesanan,
    'nama_pelanggan',     o.nama_pelanggan,
    'no_hp',              o.no_hp,
    'alamat',             o.alamat,
    'catatan',            o.catatan,
    'total_barang',       o.total_barang,
    'ongkos_kirim',       o.ongkos_kirim,
    'total_bayar',        o.total_bayar,
    'status',             o.status,
    'url_bukti_transfer', o.url_bukti_transfer,
    'dibuat_pada',        o.dibuat_pada,
    'diubah_pada',        o.diubah_pada,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',           oi.id,
        'order_id',     oi.order_id,
        'product_id',   oi.product_id,
        'nama_produk',  oi.nama_produk,
        'harga_satuan', oi.harga_satuan,
        'jumlah',       oi.jumlah,
        'subtotal',     oi.subtotal
      ) order by oi.id)
      from public.order_items oi
      where oi.order_id = o.id
    ), '[]'::jsonb)
  )
  from public.orders o
  where o.id = p_order_id;
$$;

-- ============================================================
-- RPC: BUAT PESANAN (atomik) — dipanggil tombol "Pesan Sekarang".
-- Memenuhi PRD 4.1 (cek stok ganda + kunci baris, stok berkurang saat
-- pesanan dibuat), 4.2 (harga dikunci & total dihitung ulang di server),
-- dan 4.4 (tidak percaya angka dari browser).
-- ============================================================
create or replace function public.vd_create_order(
  p_items          jsonb,     -- [{"product_id": 2, "jumlah": 3}, ...]
  p_nama_pelanggan text,
  p_no_hp          text,
  p_alamat         text,
  p_catatan        text default '',
  p_ongkos_kirim   integer default 0
)
returns jsonb
language plpgsql
security definer          -- aturan bisnis dieksekusi server, RLS dilewati DI DALAM fungsi ini saja
set search_path = ''
as $$
declare
  v_order_id     bigint;
  v_kode         text;
  v_ongkos       integer;
  v_total_barang integer := 0;
  v_item         jsonb;
  v_product      public.products%rowtype;
  v_jumlah       integer;
begin
  -- --- Validasi dasar (PRD 4.4) ---
  if p_items is null or jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Keranjang masih kosong.';
  end if;
  if char_length(btrim(coalesce(p_nama_pelanggan, ''))) < 3 then
    raise exception 'Nama penerima wajib diisi (minimal 3 karakter).';
  end if;
  if coalesce(p_no_hp, '') !~ '^[0-9]{10,15}$' then
    raise exception 'Nomor HP wajib diisi, minimal 10 angka.';
  end if;
  if char_length(btrim(coalesce(p_alamat, ''))) < 10 then
    raise exception 'Alamat pengiriman wajib diisi (minimal 10 karakter).';
  end if;

  -- --- Ongkos kirim: pakai nilai Pengaturan Toko bila tabel settings ada ---
  v_ongkos := greatest(0, coalesce(p_ongkos_kirim, 0));
  begin
    select nullif(btrim(nilai), '')::integer into v_ongkos
    from public.settings
    where kunci = 'ongkos_kirim'
    limit 1;
    if v_ongkos is null then
      v_ongkos := greatest(0, coalesce(p_ongkos_kirim, 0));
    end if;
  exception when undefined_table or undefined_column or invalid_text_representation then
    null; -- tabel settings belum siap: pakai nilai dari klien
  end;

  -- --- Pengecekan ganda stok + KUNCI baris produk (PRD 4.1) ---
  -- FOR UPDATE mencegah dua pembeli memesan stok yang sama bersamaan.
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_jumlah := greatest(1, coalesce((v_item ->> 'jumlah')::integer, 1));

    select * into v_product
    from public.products
    where id = (v_item ->> 'product_id')::bigint
    for update;

    if not found then
      raise exception 'Ada produk di keranjang yang sudah tidak tersedia.';
    end if;
    if v_product.aktif = false then
      raise exception 'Maaf, % sedang tidak dijual.', v_product.nama;
    end if;
    if v_product.stok < v_jumlah then
      raise exception 'Maaf, stok % tinggal %. Silakan sesuaikan jumlahnya.', v_product.nama, v_product.stok;
    end if;
  end loop;

  -- --- Simpan pesanan; kode = VD-YYMM-id (bebas tabrakan, contoh PRD: VD-2609-0031) ---
  insert into public.orders (kode_pesanan, nama_pelanggan, no_hp, alamat, catatan, ongkos_kirim, status)
  values ('', p_nama_pelanggan, p_no_hp, p_alamat, coalesce(p_catatan, ''), v_ongkos, 'Menunggu Pembayaran')
  returning id into v_order_id;

  v_kode := 'VD-' || to_char(now(), 'YYMM') || '-' || lpad(v_order_id::text, 4, '0');
  update public.orders set kode_pesanan = v_kode where id = v_order_id;

  -- --- Rincian item (harga dikunci) + kurangi stok + catat riwayat ---
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_jumlah := greatest(1, coalesce((v_item ->> 'jumlah')::integer, 1));

    select * into v_product
    from public.products
    where id = (v_item ->> 'product_id')::bigint
    for update;

    insert into public.order_items (order_id, product_id, nama_produk, harga_satuan, jumlah, subtotal)
    values (v_order_id, v_product.id, v_product.nama, v_product.harga, v_jumlah, v_product.harga * v_jumlah);

    update public.products
    set stok = stok - v_jumlah, diubah_pada = now()
    where id = v_product.id;

    insert into public.stock_logs (product_id, perubahan, stok_sebelum, stok_sesudah, alasan, user_id)
    values (v_product.id, -v_jumlah, v_product.stok, v_product.stok - v_jumlah, 'Pesanan ' || v_kode, null);

    v_total_barang := v_total_barang + (v_product.harga * v_jumlah);
  end loop;

  -- --- Total akhir dihitung DI SERVER (PRD 4.2/4.4) ---
  update public.orders
  set total_barang = v_total_barang,
      total_bayar  = v_total_barang + v_ongkos
  where id = v_order_id;

  return public.vd_order_jsonb(v_order_id);
end;
$$;

-- ============================================================
-- RPC: BATALKAN PESANAN — status jadi "Dibatalkan" + STOK DIKEMBALIKAN
-- sejumlah barang di pesanan (PRD 4.1). Dipakai admin & auto-expire 2 jam.
-- ============================================================
create or replace function public.vd_cancel_order(
  p_order_id bigint,
  p_alasan   text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.orders%rowtype;
  v_item  public.order_items%rowtype;
begin
  select * into v_order from public.orders where id = p_order_id for update;

  if not found then
    raise exception 'Pesanan tidak ditemukan.';
  end if;
  if v_order.status in ('Selesai', 'Dibatalkan') then
    raise exception 'Pesanan berstatus "%" tidak bisa diubah lagi.', v_order.status;
  end if;

  update public.orders set status = 'Dibatalkan' where id = v_order.id;

  for v_item in
    select * from public.order_items
    where order_id = v_order.id and product_id is not null
  loop
    update public.products
    set stok = stok + v_item.jumlah, diubah_pada = now()
    where id = v_item.product_id;

    insert into public.stock_logs (product_id, perubahan, stok_sebelum, stok_sesudah, alasan, user_id)
    select v_item.product_id, v_item.jumlah, p.stok - v_item.jumlah, p.stok,
           coalesce(nullif(btrim(p_alasan), ''), 'Pembatalan pesanan ' || v_order.kode_pesanan),
           null
    from public.products p
    where p.id = v_item.product_id;
  end loop;

  return public.vd_order_jsonb(v_order.id);
end;
$$;

-- ============================================================
-- Row Level Security
-- - Pesanan HANYA bisa dibuat lewat RPC vd_create_order (tidak ada policy
--   insert) supaya stok & total selalu dihitung ulang di server (PRD 4.4).
-- - Baca & ubah terbuka untuk MVP karena login admin masih sesi frontend;
--   perketat ke `to authenticated` + cek peran saat Supabase Auth dipasang.
-- - stock_logs tidak punya policy: ditulis hanya lewat RPC di atas.
-- ============================================================
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_logs  enable row level security;
alter table public.settings    enable row level security;

drop policy if exists "pesanan bisa dibaca" on public.orders;
create policy "pesanan bisa dibaca"
  on public.orders for select
  to anon, authenticated
  using (true);

drop policy if exists "pesanan bisa diubah" on public.orders;
create policy "pesanan bisa diubah"
  on public.orders for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "rincian pesanan bisa dibaca" on public.order_items;
create policy "rincian pesanan bisa dibaca"
  on public.order_items for select
  to anon, authenticated
  using (true);

drop policy if exists "pengaturan bisa dibaca" on public.settings;
create policy "pengaturan bisa dibaca"
  on public.settings for select
  to anon, authenticated
  using (true);

-- Izin eksekusi fungsi untuk aplikasi
grant execute on function public.vd_create_order(jsonb, text, text, text, text, integer) to anon, authenticated;
grant execute on function public.vd_cancel_order(bigint, text)                       to anon, authenticated;
grant execute on function public.vd_order_jsonb(bigint)                              to anon, authenticated;

-- ============================================================
-- (Opsional) Supabase Realtime — status pesanan ikut berubah otomatis
-- di semua browser tanpa refresh:
-- alter publication supabase_realtime add table public.orders;
-- alter publication supabase_realtime add table public.products;
-- ============================================================




-- __VD_POLICIES__
