-- ============================================================
-- VibeDonuts — Fungsi "Reset Data Demo" (RPC vd_reset_demo_data)
--
-- Tujuan: menghapus SEMUA data di Supabase lalu mengisi ulang data demo
--         yang konsisten: 3 kategori, 3 donat contoh (stok normal 24 /
--         menipis 4 / habis 0), 3 pesanan contoh + rinciannya, riwayat
--         stok yang cocok, dan pengaturan toko awal.
--
-- CATATAN: ekstensi `pg_safeupdate` (aktif bawaan Supabase) menolak
-- DELETE tanpa WHERE — karena itu semua DELETE di sini memakai
-- `where true` (pintasan resmi untuk "hapus semua baris").
--
-- PERINGATAN: menghapus permanen pesanan & produk sungguhan.
-- Jalankan di SQL Editor SETELAH 01-04.
-- ============================================================

-- ---------- Tabel kategori (juga menghilangkan warning 404 di console) ----------
create table if not exists public.categories (
  id   bigint generated by default as identity primary key,
  nama text not null,
  slug text not null unique
);

alter table public.categories enable row level security;

drop policy if exists "kategori bisa dibaca" on public.categories;
create policy "kategori bisa dibaca"
  on public.categories for select
  to anon, authenticated
  using (true);

create or replace function public.vd_reset_demo_data()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- QA: hanya admin yang boleh mereset (mencegah pengguna lain menghapus data).
  -- Bila peran belum terpasang, jalankan 08_admin_role.sql lalu vd_grant_admin.
  if not coalesce(public.vd_is_admin(), false) then
    raise exception 'Hanya admin yang boleh mereset data demo. Jalankan 08_admin_role.sql lalu select public.vd_grant_admin(''email-anda@gmail.com'');';
  end if;

  -- --- 1. Hapus semua data (urutan menghormati FK) ---
  delete from public.order_items where true;
  delete from public.orders      where true;
  delete from public.stock_logs  where true;
  delete from public.products    where true;
  delete from public.categories  where true;

  -- --- 2. Kategori contoh ---
  insert into public.categories (id, nama, slug) values
    (1, 'Klasik',  'klasik'),
    (2, 'Premium', 'premium'),
    (3, 'Musiman', 'musiman');
  perform setval(pg_get_serial_sequence('public.categories', 'id'), 3, true);

  -- --- 3. Produk contoh (id 1-3, sama dengan seed frontend) ---
  insert into public.products (id, category_id, nama, slug, deskripsi, harga, stok, url_foto, aktif) values
    (1, 2, 'Donat Tiramisu', 'donat-tiramisu',
       'Donat lembut dengan krim kopi mascarpone, ditaburi bubuk kakao Belanda dan serpihan cokelat premium.',
       18000, 24, 'https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?auto=format&fit=crop&w=900&q=80', true),
    (2, 1, 'Donat Cokelat Klasik', 'donat-cokelat-klasik',
       'Resep klasik sejak hari pertama: adonan ragi 12 jam, lapisan ganache cokelat susu, dan taburan meses lembut.',
       12000, 4, 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=900&q=80', true),
    (3, 3, 'Donat Strawberry Sprinkle', 'donat-strawberry-sprinkle',
       'Edisi musiman dengan selai stroberi asli Ciwidey, icing pastel, dan sprinkle warna-warni.',
       15000, 0, 'https://images.unsplash.com/photo-1626094309830-abbb0c99da4a?auto=format&fit=crop&w=900&q=80', true);
  perform setval(pg_get_serial_sequence('public.products', 'id'), 3, true);

  -- --- 4. Pesanan contoh (kode = VD-YYMM-id, konsisten dengan riwayat stok) ---
  insert into public.orders (id, kode_pesanan, nama_pelanggan, no_hp, alamat, catatan,
                             total_barang, ongkos_kirim, total_bayar, status,
                             url_bukti_transfer, dibuat_pada, diubah_pada)
  values
    (30, 'VD-2609-0030', 'Budi Santoso', '081234567890',
       'Jl. Melati No. 5, RT 02 / RW 04, Kudus', 'Tolong tanpa taburan kacang.',
       54000, 10000, 64000, 'Menunggu Verifikasi', '/uploads/bukti-30.jpg',
       now() - interval '3 hours',  now() - interval '2 hours'),
    (29, 'VD-2609-0029', 'Sari Dewi', '081298765432',
       'Perum Griya Asri Blok C2 No. 11, Kudus', '',
       72000, 10000, 82000, 'Diproses', '/uploads/bukti-29.jpg',
       now() - interval '27 hours', now() - interval '20 hours'),
    (28, 'VD-2609-0028', 'Andi Pratama', '085712345678',
       'Jl. Sunan Kudus No. 88, Kudus', 'Titip di pos keamanan ya.',
       90000, 10000, 100000, 'Selesai', '/uploads/bukti-28.jpg',
       now() - interval '74 hours', now() - interval '50 hours');
  perform setval(pg_get_serial_sequence('public.orders', 'id'), 30, true);

  insert into public.order_items (id, order_id, product_id, nama_produk, harga_satuan, jumlah, subtotal) values
    (1, 30, 1, 'Donat Tiramisu',            18000, 3, 54000),
    (2, 29, 2, 'Donat Cokelat Klasik',      12000, 6, 72000),
    (3, 28, 3, 'Donat Strawberry Sprinkle', 15000, 6, 90000);
  perform setval(pg_get_serial_sequence('public.order_items', 'id'), 3, true);

  -- --- 5. Riwayat stok yang konsisten dengan stok akhir produk ---
  insert into public.stock_logs (id, product_id, perubahan, stok_sebelum, stok_sesudah, alasan, user_id, dibuat_pada) values
    (1, 1,  27, 0, 27, 'Produksi baru batch pagi', null, now() - interval '30 hours'),
    (2, 2,  10, 0, 10, 'Produksi baru batch pagi', null, now() - interval '30 hours'),
    (3, 3,   6, 0,  6, 'Produksi baru batch pagi', null, now() - interval '30 hours'),
    (4, 1,  -3, 27, 24, 'Pesanan VD-2609-0030', null, now() - interval '3 hours'),
    (5, 2,  -6, 10,  4, 'Pesanan VD-2609-0029', null, now() - interval '27 hours'),
    (6, 3,  -6,  6,  0, 'Pesanan VD-2609-0028', null, now() - interval '74 hours');
  perform setval(pg_get_serial_sequence('public.stock_logs', 'id'), 6, true);

  -- --- 6. Pengaturan toko kembali ke nilai awal ---
  insert into public.settings (kunci, nilai) values
    ('ongkos_kirim', '10000'),
    ('nomor_rekening', '1234567890'),
    ('nama_bank', 'BCA'),
    ('atas_nama', 'Rina VibeDonuts'),
    ('whatsapp_toko', '6281234567890')
  on conflict (kunci) do update set nilai = excluded.nilai;
end;
$$;

grant execute on function public.vd_reset_demo_data() to anon, authenticated;
